timeline:
  storyline_1:
    name: Storyline 1
    description: This is storyline 1
    # The name of the world where the storyline is located
    arc: arc_1
    # Timeline's number of quests
    quests_length: 2
    # Quest list
    # "END" means the end of the storyline
    onStart:
      quests:
        - quest1
        - quest2
    onEnd:
      notice: You have completed storyline 1
      rewards:
        give:
          items:
            "gold:1"

language: en
message-format: "&7[&6Mysticover&7] &r%message%"

first_arc: arc_1

database:
  # The database type. "sqlite" and "mysql" are supported.
  type: sqlite

  # Edit these settings only if you choose "sqlite".
  sqlite:
    # The file name of the database in the plugin data folder.
    # You can also put an absolute path here.
    file: data.sqlite
  # Edit these settings only if you choose "mysql".
  mysql:
    host: 127.0.0.1
    # Avoid using the "root" user for security reasons.
    username: root
    password: ""
    schema: your_schema
  # The maximum number of simultaneous SQL queries
  # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 1